/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista;

import java.awt.event.ActionListener;
import java.util.Date;
import java.util.List;
import javax.swing.JComboBox;
import modelo.Permiso;
import modelo.Rango;

/**
 *
 * @author alumno
 */
public class CrearModificarUsuariosDialogVista extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CrearModificarUsuariosDialogVista.class.getName());

    /**
     * Creates new form crearModificarUsuariosDialogVista
     */
    public CrearModificarUsuariosDialogVista(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setTitle("Role Police Manager - Crea/Modifica Usuario");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        nombreLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        rangoLabel = new javax.swing.JLabel();
        estadoLabel = new javax.swing.JLabel();
        permisosLabel = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        cbRango = new javax.swing.JComboBox<>();
        cbEstado = new javax.swing.JComboBox<>();
        cbPermisos = new javax.swing.JComboBox<>();
        fechaIngresoLabel = new javax.swing.JLabel();
        fechaUltimoAscensoLabel = new javax.swing.JLabel();
        dateChooserFechaIngreso = new com.toedter.calendar.JDateChooser();
        dateChooserFechaUltimoAscenso = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnAceptar.setText("Aceptar");

        btnCancelar.setText("Cancelar");

        nombreLabel.setText("Nombre:");

        emailLabel.setText("Email:");

        rangoLabel.setText("Rango:");

        estadoLabel.setText("Estado:");

        permisosLabel.setText("Nivel de permisos:");

        txtNombre.setText("");

        txtEmail.setText("");

        fechaIngresoLabel.setText("Fecha ingreso:");

        fechaUltimoAscensoLabel.setText("Fecha ultimo ascenso:");

        dateChooserFechaIngreso.setDateFormatString("dd/MM/yyyy");

        dateChooserFechaUltimoAscenso.setDateFormatString("dd/MM/yyyy");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAceptar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nombreLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombre))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(emailLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmail))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rangoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbRango, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(permisosLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbPermisos, 0, 194, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(estadoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbEstado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fechaUltimoAscensoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateChooserFechaUltimoAscenso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fechaIngresoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateChooserFechaIngreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreLabel)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rangoLabel)
                    .addComponent(cbRango, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(estadoLabel)
                    .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(permisosLabel)
                    .addComponent(cbPermisos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fechaIngresoLabel)
                    .addComponent(dateChooserFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fechaUltimoAscensoLabel)
                    .addComponent(dateChooserFechaUltimoAscenso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public String getTxtEmail() {
        return this.txtEmail.getText();
    }

    public void setTxtEmail(String txtEmail) {
        this.txtEmail.setText(txtEmail);
    }

    public String getTxtNombre() {
        return this.txtNombre.getText();
    }

    public void setTxtNombre(String txtNombre) {
        this.txtNombre.setText(txtNombre);
    }

    public void cbEstadoActionListener(ActionListener listener) {
        this.cbEstado.addActionListener(listener);
    }

    public void setEstado(String estado) {
        cbEstado.setSelectedItem(estado);
    }

    public void setEstados(String[] estados) {
        cbEstado.removeAllItems();
        for (String e : estados) {
            cbEstado.addItem(e);
        }
    }

    public String getEstado() {
        return this.cbEstado.getItemAt(this.cbEstado.getSelectedIndex());
    }

    public void setRangos(List<Rango> rangos) {
        cbRango.removeAllItems();
        for (modelo.Rango r : rangos) {
            cbRango.addItem(r);
        }
    }

    public modelo.Rango getRangoSeleccionado() {
        return (modelo.Rango) cbRango.getSelectedItem();
    }

    public void setPermisos(List<Permiso> permisos) {
        cbPermisos.removeAllItems();
        for (modelo.Permiso p : permisos) {
            cbPermisos.addItem(p);
        }
    }

    public Permiso getPermisoSeleccionado() {
        return (Permiso) cbPermisos.getSelectedItem();
    }

    public void addAceptarListener(ActionListener al) {
        btnAceptar.addActionListener(al);
    }

    public void addCancelarListener(ActionListener al) {
        btnCancelar.addActionListener(al);
    }

    public JComboBox<Rango> getRangoCombo() {
        return cbRango;
    }

    public JComboBox<modelo.Permiso> getPermisoCombo() {
        return cbPermisos;
    }

    public Date getFechaIngreso() {
        return dateChooserFechaIngreso.getDate();
    }

    public void setFechaIngreso(Date fecha) {
        dateChooserFechaIngreso.setDate(fecha);
    }

    public Date getFechaUltimoAscenso() {
        return dateChooserFechaUltimoAscenso.getDate();
    }

    public void setFechaUltimoAscenso(Date fecha) {
        dateChooserFechaUltimoAscenso.setDate(fecha);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<String> cbEstado;
    private javax.swing.JComboBox<Permiso> cbPermisos;
    private javax.swing.JComboBox<Rango> cbRango;
    private com.toedter.calendar.JDateChooser dateChooserFechaIngreso;
    private com.toedter.calendar.JDateChooser dateChooserFechaUltimoAscenso;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel estadoLabel;
    private javax.swing.JLabel fechaIngresoLabel;
    private javax.swing.JLabel fechaUltimoAscensoLabel;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JLabel permisosLabel;
    private javax.swing.JLabel rangoLabel;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
