package vista;

import java.awt.event.ActionListener;
import java.awt.event.KeyListener;
import java.awt.event.MouseListener;
import java.util.List;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import modelo.Division;

/**
 *
 * @author usuario
 */
public class DivisionesVista extends JFrame {

    private static final Logger logger = Logger.getLogger(DivisionesVista.class.getName());
    private DefaultTableModel modeloTabla;

    /**
     * Creates new form DivisionesVista
     */
    public DivisionesVista() {
        initComponents();
        this.setTitle("Role Police Manager - Divisiones");
        this.setLocationRelativeTo(null);

        String[] columnas = {"ID", "Nombre", "Descripción", "Responsable", "Nº Miembros"};
        modeloTabla = new DefaultTableModel(columnas, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        tablaDivisiones.setModel(modeloTabla);

        tablaDivisiones.getColumnModel().getColumn(0).setMinWidth(0);
        tablaDivisiones.getColumnModel().getColumn(0).setMaxWidth(0);
        tablaDivisiones.getColumnModel().getColumn(0).setWidth(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDivisiones = new javax.swing.JTable();
        btnCrear = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        btnGestionarMiembros = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tablaDivisiones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaDivisiones);

        btnCrear.setText("Crear División");

        btnEditar.setText("Editar");

        btnEliminar.setBackground(new java.awt.Color(204, 0, 0));
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");

        txtBuscar.setText("");

        btnGestionarMiembros.setText("Gestionar Miembros");

        jLabel1.setText("Buscar:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnGestionarMiembros)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCrear))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrear)
                    .addComponent(btnEditar)
                    .addComponent(btnEliminar)
                    .addComponent(btnGestionarMiembros))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void cargarDivisiones(List<Division> divisiones) {
        modeloTabla.setRowCount(0);
        for (Division division : divisiones) {
            Object[] fila = {
                division.getIdDivision(),
                division.getNombre(),
                division.getDescripcion(),
                division.getNombreResponsable() != null ? division.getNombreResponsable() : "Sin asignar",
                BD.DivisionBD.contarMiembrosDivision(division.getIdDivision())
            };
            modeloTabla.addRow(fila);
        }
    }

    public Division getDivisionSeleccionada() {
        int filaSeleccionada = tablaDivisiones.getSelectedRow();
        if (filaSeleccionada == -1) {
            return null;
        }

        Division division = new Division();
        division.setIdDivision((int) modeloTabla.getValueAt(filaSeleccionada, 0));
        division.setNombre((String) modeloTabla.getValueAt(filaSeleccionada, 1));
        division.setDescripcion((String) modeloTabla.getValueAt(filaSeleccionada, 2));

        return division;
    }

    public int getIdDivisionSeleccionada() {
        int filaSeleccionada = tablaDivisiones.getSelectedRow();
        if (filaSeleccionada == -1) {
            return -1;
        }
        return (int) modeloTabla.getValueAt(filaSeleccionada, 0);
    }

    public String getTextoBusqueda() {
        return txtBuscar.getText().trim();
    }

    public void limpiarSeleccion() {
        tablaDivisiones.clearSelection();
    }

    public void addBtnCrearListener(ActionListener listener) {
        btnCrear.addActionListener(listener);
    }

    public void addBtnEditarListener(ActionListener listener) {
        btnEditar.addActionListener(listener);
    }

    public void addBtnEliminarListener(ActionListener listener) {
        btnEliminar.addActionListener(listener);
    }

    public void addBtnGestionarMiembrosListener(ActionListener listener) {
        btnGestionarMiembros.addActionListener(listener);
    }

    public void addTxtBuscarListener(KeyListener listener) {
        txtBuscar.addKeyListener(listener);
    }

    public void addTablaMouseListener(MouseListener listener) {
        tablaDivisiones.addMouseListener(listener);
    }

    public JButton getBtnCrear() {
        return btnCrear;
    }

    public JButton getBtnEditar() {
        return btnEditar;
    }

    public JButton getBtnEliminar() {
        return btnEliminar;
    }

    public JButton getBtnGestionarMiembros() {
        return btnGestionarMiembros;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGestionarMiembros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaDivisiones;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
