package vista;

import java.awt.BorderLayout;
import java.util.List;
import javax.swing.JLabel;
import modelo.Estadistica;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author roi conles ferro
 */
public class EstadisticasVista extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EstadisticasVista.class.getName());

    /**
     * Creates new form EstadisticasVista
     */
    public EstadisticasVista() {
        initComponents();
        this.setTitle("Role Police Manager - Estadísticas");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblNumeroUsuarios = new javax.swing.JLabel();
        tabbedPaneGraficos = new javax.swing.JTabbedPane();
        panelGraficoDivisiones = new javax.swing.JPanel();
        panelGraficoLicencias = new javax.swing.JPanel();
        panelGraficoActividad = new javax.swing.JPanel();
        panelGraficoRangos = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblNumeroDivisiones = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblNumeroLicencias = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lblNumeroInformes = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lblNumeroAnuncios = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lblNumeroLogs = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Resumen:");

        jLabel2.setText("Usuarios");

        lblNumeroUsuarios.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        lblNumeroUsuarios.setText("000");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNumeroUsuarios)
                    .addComponent(jLabel2))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(lblNumeroUsuarios)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelGraficoDivisionesLayout = new javax.swing.GroupLayout(panelGraficoDivisiones);
        panelGraficoDivisiones.setLayout(panelGraficoDivisionesLayout);
        panelGraficoDivisionesLayout.setHorizontalGroup(
            panelGraficoDivisionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 569, Short.MAX_VALUE)
        );
        panelGraficoDivisionesLayout.setVerticalGroup(
            panelGraficoDivisionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 171, Short.MAX_VALUE)
        );

        tabbedPaneGraficos.addTab("Divisiones", panelGraficoDivisiones);

        javax.swing.GroupLayout panelGraficoLicenciasLayout = new javax.swing.GroupLayout(panelGraficoLicencias);
        panelGraficoLicencias.setLayout(panelGraficoLicenciasLayout);
        panelGraficoLicenciasLayout.setHorizontalGroup(
            panelGraficoLicenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 569, Short.MAX_VALUE)
        );
        panelGraficoLicenciasLayout.setVerticalGroup(
            panelGraficoLicenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 171, Short.MAX_VALUE)
        );

        tabbedPaneGraficos.addTab("Licencias", panelGraficoLicencias);

        javax.swing.GroupLayout panelGraficoActividadLayout = new javax.swing.GroupLayout(panelGraficoActividad);
        panelGraficoActividad.setLayout(panelGraficoActividadLayout);
        panelGraficoActividadLayout.setHorizontalGroup(
            panelGraficoActividadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 569, Short.MAX_VALUE)
        );
        panelGraficoActividadLayout.setVerticalGroup(
            panelGraficoActividadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 171, Short.MAX_VALUE)
        );

        tabbedPaneGraficos.addTab("Actividad", panelGraficoActividad);

        javax.swing.GroupLayout panelGraficoRangosLayout = new javax.swing.GroupLayout(panelGraficoRangos);
        panelGraficoRangos.setLayout(panelGraficoRangosLayout);
        panelGraficoRangosLayout.setHorizontalGroup(
            panelGraficoRangosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 569, Short.MAX_VALUE)
        );
        panelGraficoRangosLayout.setVerticalGroup(
            panelGraficoRangosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 171, Short.MAX_VALUE)
        );

        tabbedPaneGraficos.addTab("Rangos", panelGraficoRangos);

        jLabel3.setText("Divisiones");

        lblNumeroDivisiones.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        lblNumeroDivisiones.setText("000");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(lblNumeroDivisiones)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(lblNumeroDivisiones)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setText("Licencias");

        lblNumeroLicencias.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        lblNumeroLicencias.setText("000");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel4))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lblNumeroLicencias)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(lblNumeroLicencias)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setText("Informes");

        lblNumeroInformes.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        lblNumeroInformes.setText("000");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNumeroInformes)
                    .addComponent(jLabel5))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(lblNumeroInformes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setText("Anuncios");

        lblNumeroAnuncios.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        lblNumeroAnuncios.setText("000");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNumeroAnuncios)
                    .addComponent(jLabel6))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(lblNumeroAnuncios)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel7.setText("Logs");

        lblNumeroLogs.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        lblNumeroLogs.setText("000");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNumeroLogs)
                    .addComponent(jLabel7))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(lblNumeroLogs)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabbedPaneGraficos)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tabbedPaneGraficos)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public String getLblNumeroAnuncios() {
        return lblNumeroAnuncios.getText();
    }

    public void setLblNumeroAnuncios(String t) {
        this.lblNumeroAnuncios.setText(t);
    }

    public String getLblNumeroDivisiones() {
        return lblNumeroDivisiones.getText();
    }

    public void setLblNumeroDivisiones(String t) {
        this.lblNumeroDivisiones.setText(t);
    }

    public String getLblNumeroInformes() {
        return lblNumeroInformes.getText();
    }

    public void setLblNumeroInformes(String t) {
        this.lblNumeroInformes.setText(t);
    }

    public String getLblNumeroLicencias() {
        return lblNumeroLicencias.getText();
    }

    public void setLblNumeroLicencias(String t) {
        this.lblNumeroLicencias.setText(t);
    }

    public String getLblNumeroLogs() {
        return lblNumeroLogs.getText();
    }

    public void setLblNumeroLogs(String t) {
        this.lblNumeroLogs.setText(t);
    }

    public String getLblNumeroUsuarios() {
        return lblNumeroUsuarios.getText();
    }

    public void setLblNumeroUsuarios(String t) {
        this.lblNumeroUsuarios.setText(t);
    }

    // Método para establecer el resumen, los 6 números
    public void setResumen(int usuarios, int divisiones, int licencias, int informes, int anuncios, int logs) {
        setLblNumeroUsuarios(String.valueOf(usuarios));
        setLblNumeroDivisiones(String.valueOf(divisiones));
        setLblNumeroLicencias(String.valueOf(licencias));
        setLblNumeroInformes(String.valueOf(informes));
        setLblNumeroAnuncios(String.valueOf(anuncios));
        setLblNumeroLogs(String.valueOf(logs));
    }

    //Metodo para cargar grafico de barras > Divisiones
    public void cargarGraficoDivisiones(List<Estadistica> datos) {
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();

        //Recorremos los datos
        for (Estadistica stat : datos) {
            dataset.addValue(stat.getValor(), "Usuarios", stat.getNombre());    //Añade: valor, usuarios y nombre
        }

        //Creacion del grafico de barras > Titulo > Eje X > Eje Y > Datos > Orientacion vertical > Leyenda > Tooltips > URLs
        JFreeChart chart = ChartFactory.createBarChart("Distribución de Usuarios por División",
                "División",
                "Número de Usuarios",
                dataset,
                PlotOrientation.VERTICAL, false, true, false);

        //Panel que contiene el grafico
        ChartPanel chartPanel = new ChartPanel(chart);

        panelGraficoDivisiones.removeAll();                             //Limpiamos el panel
        panelGraficoDivisiones.setLayout(new BorderLayout());           //Layout del panel
        panelGraficoDivisiones.add(chartPanel, BorderLayout.CENTER);    //Añade el grafico al centro
        panelGraficoDivisiones.validate();                              //Actualiza el panel
        panelGraficoDivisiones.repaint();                               //Dibuja el grafico
    }

    //Metodo para cargar grafico de tarta > Licencias
    public void cargarGraficoLicencias(List<Estadistica> datos) {
        DefaultPieDataset dataset = new DefaultPieDataset();

        //Recorremos los datos
        for (Estadistica stat : datos) {
            dataset.setValue(stat.getNombre(), stat.getValor());
        }

        JFreeChart chart = ChartFactory.createPieChart(
                "Licencias Más Asignadas",
                dataset,
                true,
                true,
                false
        );

        ChartPanel chartPanel = new ChartPanel(chart);

        panelGraficoLicencias.removeAll();
        panelGraficoLicencias.setLayout(new BorderLayout());
        panelGraficoLicencias.add(chartPanel, BorderLayout.CENTER);
        panelGraficoLicencias.validate();
        panelGraficoLicencias.repaint();
    }

    //Metodo para cargar grafico de barras > Actividad
    public void cargarGraficoActividad(List<Estadistica> datos) {
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();

        //Recorremos los datos
        for (Estadistica stat : datos) {
            dataset.addValue(stat.getValor(), "Acciones", stat.getNombre());
        }

        JFreeChart chart = ChartFactory.createBarChart(
                "Actividad por Módulo",
                "Módulo",
                "Número de Acciones",
                dataset,
                PlotOrientation.HORIZONTAL,
                false,
                true,
                false
        );

        ChartPanel chartPanel = new ChartPanel(chart);

        panelGraficoActividad.removeAll();
        panelGraficoActividad.setLayout(new BorderLayout());
        panelGraficoActividad.add(chartPanel, BorderLayout.CENTER);
        panelGraficoActividad.validate();
        panelGraficoActividad.repaint();
    }

    //Método para cargar gráfico de barras > Rangos
    public void cargarGraficoRangos(List<Estadistica> datos) {
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();

        //Recorremos los datos
        for (Estadistica stat : datos) {
            dataset.addValue(stat.getValor(), "Usuarios", stat.getNombre());
        }

        JFreeChart chart = ChartFactory.createBarChart(
                "Distribución de Usuarios por Rango",
                "Rango",
                "Número de Usuarios",
                dataset,
                PlotOrientation.VERTICAL,
                false,
                true,
                false
        );

        ChartPanel chartPanel = new ChartPanel(chart);

        panelGraficoRangos.removeAll();
        panelGraficoRangos.setLayout(new BorderLayout());
        panelGraficoRangos.add(chartPanel, BorderLayout.CENTER);
        panelGraficoRangos.validate();
        panelGraficoRangos.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel lblNumeroAnuncios;
    private javax.swing.JLabel lblNumeroDivisiones;
    private javax.swing.JLabel lblNumeroInformes;
    private javax.swing.JLabel lblNumeroLicencias;
    private javax.swing.JLabel lblNumeroLogs;
    private javax.swing.JLabel lblNumeroUsuarios;
    private javax.swing.JPanel panelGraficoActividad;
    private javax.swing.JPanel panelGraficoDivisiones;
    private javax.swing.JPanel panelGraficoLicencias;
    private javax.swing.JPanel panelGraficoRangos;
    private javax.swing.JTabbedPane tabbedPaneGraficos;
    // End of variables declaration//GEN-END:variables
}
