package vista;

import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.DefaultListModel;
import modelo.Usuario;

/**
 *
 * @author roi conles ferro
 */
public class GestionarMiembrosDivisionDialogVista extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GestionarMiembrosDivisionDialogVista.class.getName());
    private DefaultListModel<Usuario> modeloLibres = new DefaultListModel<>();
    private DefaultListModel<Usuario> modeloMiembros = new DefaultListModel<>();

    /**
     * Creates new form GestionarMiembrosDivisionDialogVista
     */
    public GestionarMiembrosDivisionDialogVista(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ListaUsuariosLibres = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListaMiembros = new javax.swing.JList<>();
        btnVolver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnQuitar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setViewportView(ListaUsuariosLibres);

        jScrollPane2.setViewportView(ListaMiembros);

        btnVolver.setText("Volver");

        jLabel1.setText("Usuarios disponibles");

        jLabel2.setText("Miembros");

        btnQuitar.setText("Quitar");

        btnAgregar.setText("Añadir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnVolver))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAgregar)
                                    .addComponent(btnQuitar))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(btnAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnQuitar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(btnVolver)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void cargarUsuariosDisponibles(List<Usuario> usuarios) {
        modeloLibres.clear();
        for (Usuario u : usuarios) {
            modeloLibres.addElement(u);
        }
        ListaUsuariosLibres.setModel(modeloLibres);
    }

    public void cargarMiembros(List<Usuario> usuarios) {
        modeloMiembros.clear();
        for (Usuario u : usuarios) {
            modeloMiembros.addElement(u);
        }
        ListaMiembros.setModel(modeloMiembros);
    }

    public Usuario getUsuarioLibreSeleccionado() {
        return ListaUsuariosLibres.getSelectedValue();
    }

    public Usuario getMiembroSeleccionado() {
        return ListaMiembros.getSelectedValue();
    }

    public void limpiarSelecciones() {
        ListaUsuariosLibres.clearSelection();
        ListaMiembros.clearSelection();
    }

    public void setNombreDivision(String nombre) {
        this.setTitle("Gestión de Miembros - " + nombre);
    }

    public void addAgregarListener(ActionListener al) {
        btnAgregar.addActionListener(al);
    }

    public void addQuitarListener(ActionListener al) {
        btnQuitar.addActionListener(al);
    }

    public void addVolverListener(ActionListener al) {
        btnVolver.addActionListener(al);
    }

    public void cerrar() {
        dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<Usuario> ListaMiembros;
    private javax.swing.JList<Usuario> ListaUsuariosLibres;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnQuitar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
