package vista;

import java.awt.event.ActionListener;
import java.awt.event.KeyListener;
import java.awt.event.MouseListener;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JButton;
import javax.swing.table.DefaultTableModel;
import modelo.Informe;
import modelo.Usuario;

/**
 *
 * @author roi conles ferro
 */
public class InformesVista extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InformesVista.class.getName());
    private DefaultTableModel modeloTabla;

    /**
     * Creates new form InformesVista
     */
    public InformesVista() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Role Police Manager - Informes");

        String[] columnas = {"ID", "Evaluador", "Evaluado", "Fecha"};
        modeloTabla = new DefaultTableModel(columnas, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        tablaInformes.setModel(modeloTabla);

        // Ocultar columna ID
        tablaInformes.getColumnModel().getColumn(0).setMinWidth(0);
        tablaInformes.getColumnModel().getColumn(0).setMaxWidth(0);
        tablaInformes.getColumnModel().getColumn(0).setWidth(0);

        // Configurar combo filtro
        cmbFiltro.removeAllItems();
        cmbFiltro.addItem("Todos");
        cmbFiltro.addItem("Realizados por mí");
        cmbFiltro.addItem("Sobre usuario específico");

        // Deshabilitar combo usuario inicialmente
        cmbUsuario.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaInformes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        cmbFiltro = new javax.swing.JComboBox<>();
        cmbUsuario = new javax.swing.JComboBox<>();
        txtBuscar = new javax.swing.JTextField();
        btnCrear = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnVer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tablaInformes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaInformes);

        jLabel1.setText("Filtrar:");

        txtBuscar.setText("");

        btnCrear.setText("Crear");

        btnEliminar.setBackground(new java.awt.Color(204, 0, 0));
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");

        btnVer.setText("Ver Contenido");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnVer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCrear)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrear)
                    .addComponent(btnEliminar)
                    .addComponent(btnVer))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void cargarInformes(List<Informe> informes) {
        modeloTabla.setRowCount(0);
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        for (Informe informe : informes) {
            Object[] fila = {
                informe.getIdInforme(),
                informe.getNombreEvaluador(),
                informe.getNombreEvaluado(),
                informe.getFecha() != null ? sdf.format(informe.getFecha()) : ""
            };
            modeloTabla.addRow(fila);
        }
    }

    public Informe getInformeSeleccionado() {
        int filaSeleccionada = tablaInformes.getSelectedRow();
        if (filaSeleccionada == -1) {
            return null;
        }

        int idInforme = (int) modeloTabla.getValueAt(filaSeleccionada, 0);
        return BD.InformeBD.obtenerInformePorId(idInforme);
    }

    public int getIdInformeSeleccionado() {
        int filaSeleccionada = tablaInformes.getSelectedRow();
        if (filaSeleccionada == -1) {
            return -1;
        }
        return (int) modeloTabla.getValueAt(filaSeleccionada, 0);
    }

    public String getTextoBusqueda() {
        return txtBuscar.getText().trim();
    }

    public String getFiltroSeleccionado() {
        return (String) cmbFiltro.getSelectedItem();
    }

    public Usuario getUsuarioFiltroSeleccionado() {
        return (Usuario) cmbUsuario.getSelectedItem();
    }

    public void cargarUsuariosEnFiltro(List<Usuario> usuarios) {
        cmbUsuario.removeAllItems();
        for (Usuario u : usuarios) {
            cmbUsuario.addItem(u);
        }
    }

    public void habilitarComboUsuario(boolean habilitar) {
        cmbUsuario.setEnabled(habilitar);
    }

    public void limpiarSeleccion() {
        tablaInformes.clearSelection();
    }

    public JButton getBtnCrear() {
        return btnCrear;
    }

    public JButton getBtnVer() {
        return btnVer;
    }

    public JButton getBtnEliminar() {
        return btnEliminar;
    }

    public void addBtnCrearListener(ActionListener listener) {
        btnCrear.addActionListener(listener);
    }

    public void addBtnVerListener(ActionListener listener) {
        btnVer.addActionListener(listener);
    }

    public void addBtnEliminarListener(ActionListener listener) {
        btnEliminar.addActionListener(listener);
    }

    public void addCmbFiltroListener(ActionListener listener) {
        cmbFiltro.addActionListener(listener);
    }

    public void addCmbUsuarioListener(ActionListener listener) {
        cmbUsuario.addActionListener(listener);
    }

    public void addTxtBuscarListener(KeyListener listener) {
        txtBuscar.addKeyListener(listener);
    }

    public void addTablaMouseListener(MouseListener listener) {
        tablaInformes.addMouseListener(listener);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnVer;
    private javax.swing.JComboBox<String> cmbFiltro;
    private javax.swing.JComboBox<Usuario> cmbUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaInformes;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
