package vista;

import java.awt.event.ActionListener;
import java.awt.event.KeyListener;
import java.awt.event.MouseListener;
import java.util.List;
import javax.swing.JButton;
import javax.swing.table.DefaultTableModel;
import modelo.Licencia;

/**
 *
 * @author usuario
 */
public class LicenciasVista extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LicenciasVista.class.getName());
    private DefaultTableModel modeloTabla;

    /**
     * Creates new form LicenciasVista
     */
    public LicenciasVista() {
        initComponents();
        this.setTitle("Role Police Manager - Licencias");
        this.setLocationRelativeTo(null);

        String[] columnas = {"ID", "Nombre", "Descripción", "Nº Usuarios"};
        modeloTabla = new DefaultTableModel(columnas, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        tablaLicencias.setModel(modeloTabla);

        // Ocultar columna ID
        tablaLicencias.getColumnModel().getColumn(0).setMinWidth(0);
        tablaLicencias.getColumnModel().getColumn(0).setMaxWidth(0);
        tablaLicencias.getColumnModel().getColumn(0).setWidth(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaLicencias = new javax.swing.JTable();
        txtBuscar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnCrear = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnGestionarLicencias = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tablaLicencias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaLicencias);

        txtBuscar.setText("");

        jLabel1.setText("Buscar:");

        btnCrear.setText("Crear");

        btnEditar.setText("Editar");

        btnEliminar.setBackground(new java.awt.Color(204, 0, 0));
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");

        btnGestionarLicencias.setText("Gestionar Licencia");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnGestionarLicencias)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCrear)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrear)
                    .addComponent(btnEditar)
                    .addComponent(btnEliminar)
                    .addComponent(btnGestionarLicencias))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void cargarLicencias(List<Licencia> licencias) {
        modeloTabla.setRowCount(0);
        for (Licencia licencia : licencias) {
            Object[] fila = {
                licencia.getIdLicencia(),
                licencia.getNombre(),
                licencia.getDescripcion(),
                BD.LicenciaBD.contarUsuariosConLicencia(licencia.getIdLicencia())
            };
            modeloTabla.addRow(fila);
        }
    }

    public Licencia getLicenciaSeleccionada() {
        int filaSeleccionada = tablaLicencias.getSelectedRow();
        if (filaSeleccionada == -1) {
            return null;
        }

        Licencia licencia = new Licencia();
        licencia.setIdLicencia((int) modeloTabla.getValueAt(filaSeleccionada, 0));
        licencia.setNombre((String) modeloTabla.getValueAt(filaSeleccionada, 1));
        licencia.setDescripcion((String) modeloTabla.getValueAt(filaSeleccionada, 2));

        return licencia;
    }

    public int getIdLicenciaSeleccionada() {
        int filaSeleccionada = tablaLicencias.getSelectedRow();
        if (filaSeleccionada == -1) {
            return -1;
        }
        return (int) modeloTabla.getValueAt(filaSeleccionada, 0);
    }

    public String getTextoBusqueda() {
        return txtBuscar.getText().trim();
    }

    public void limpiarSeleccion() {
        tablaLicencias.clearSelection();
    }

    public JButton getBtnCrear() {
        return btnCrear;
    }

    public JButton getBtnEditar() {
        return btnEditar;
    }

    public JButton getBtnEliminar() {
        return btnEliminar;
    }

    public JButton getBtnGestionarUsuarios() {
        return btnGestionarLicencias;
    }

    public void addBtnCrearListener(ActionListener listener) {
        btnCrear.addActionListener(listener);
    }

    public void addBtnEditarListener(ActionListener listener) {
        btnEditar.addActionListener(listener);
    }

    public void addBtnEliminarListener(ActionListener listener) {
        btnEliminar.addActionListener(listener);
    }

    public void addBtnGestionarUsuariosListener(ActionListener listener) {
        btnGestionarLicencias.addActionListener(listener);
    }

    public void addTxtBuscarListener(KeyListener listener) {
        txtBuscar.addKeyListener(listener);
    }

    public void addTablaMouseListener(MouseListener listener) {
        tablaLicencias.addMouseListener(listener);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGestionarLicencias;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaLicencias;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
