package vista;

import java.awt.event.ActionListener;
import modelo.Usuario;

/**
 *
 * @author alumno
 */
public class PrincipalVista extends javax.swing.JFrame {

    private Usuario usuario;
    
    public PrincipalVista(Usuario usuario) {
        initComponents();
        this.setTitle("Role Police Manager");
        this.usuario = usuario;
        bienvenidaLabel.setText("Bienvenido/a, " + usuario.getNombreRol());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bienvenidaLabel = new javax.swing.JLabel();
        btnAdministrarUsuarios = new javax.swing.JButton();
        btnLogs = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bienvenidaLabel.setText("");

        btnAdministrarUsuarios.setText("Administrar Usuarios");
        btnAdministrarUsuarios.addActionListener(this::btnAdministrarUsuariosActionPerformed);

        btnLogs.setText("Registro de logs");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bienvenidaLabel)
                    .addComponent(btnAdministrarUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLogs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(254, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bienvenidaLabel)
                .addGap(18, 18, 18)
                .addComponent(btnAdministrarUsuarios)
                .addGap(18, 18, 18)
                .addComponent(btnLogs)
                .addContainerGap(197, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdministrarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdministrarUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdministrarUsuariosActionPerformed

    public void addAdministrarUsuariosListener(ActionListener al){
        btnAdministrarUsuarios.addActionListener(al);
    }
    
    public void addRegistroLogsListener(ActionListener al){
        btnLogs.addActionListener(al);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bienvenidaLabel;
    private javax.swing.JButton btnAdministrarUsuarios;
    private javax.swing.JButton btnLogs;
    // End of variables declaration//GEN-END:variables
}
