package vista;

import java.awt.event.ActionListener;
import modelo.Usuario;

/**
 *
 * @author roi conles ferro
 */
public class PrincipalVista extends javax.swing.JFrame {

    private Usuario usuario;
    
    public PrincipalVista(Usuario usuario) {
        initComponents();
        this.setTitle("Role Police Manager");
        this.usuario = usuario;
        bienvenidaLabel.setText("Bienvenido/a, " + usuario.getNombreRol());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bienvenidaLabel = new javax.swing.JLabel();
        btnAdministrarUsuarios = new javax.swing.JButton();
        btnLogs = new javax.swing.JButton();
        btnAnuncios = new javax.swing.JButton();
        btnNormativa = new javax.swing.JButton();
        btnDivisiones = new javax.swing.JButton();
        btnLicencias = new javax.swing.JButton();
        btnInformes = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        btnEstadisticas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bienvenidaLabel.setText("");

        btnAdministrarUsuarios.setText("Administrar Usuarios");
        btnAdministrarUsuarios.addActionListener(this::btnAdministrarUsuariosActionPerformed);

        btnLogs.setText("Registro de logs");

        btnAnuncios.setText("Anuncios");

        btnNormativa.setText("Normativas");

        btnDivisiones.setText("Divisiones");

        btnLicencias.setText("Licencias");

        btnInformes.setText("Informes");

        btnCerrarSesion.setText("Cerrar Sesion");

        btnEstadisticas.setText("Estadisiticas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bienvenidaLabel)
                    .addComponent(btnAdministrarUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLogs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnInformes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEstadisticas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnLicencias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDivisiones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNormativa, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                    .addComponent(btnAnuncios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCerrarSesion)
                .addGap(105, 105, 105))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bienvenidaLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdministrarUsuarios)
                    .addComponent(btnAnuncios))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogs)
                    .addComponent(btnNormativa))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDivisiones)
                    .addComponent(btnInformes))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLicencias)
                    .addComponent(btnEstadisticas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addComponent(btnCerrarSesion)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdministrarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdministrarUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdministrarUsuariosActionPerformed

    public void addBtnAdministrarUsuariosListener(ActionListener al){
        btnAdministrarUsuarios.addActionListener(al);
    }
    
    public void addBtnRegistroLogsListener(ActionListener al){
        btnLogs.addActionListener(al);
    }
    
    public void btnAdministrarUsuariosEnable(boolean enable){
        btnAdministrarUsuarios.setEnabled(enable);
    }
    
    public void btnRegistroLogsEnable(boolean enable){
        btnLogs.setEnabled(enable);
    }
    
    public void btnInformesEnable(boolean enable){
        btnInformes.setEnabled(enable);
    }
    
    public void addBtnAnunciosListener(ActionListener al){
        btnAnuncios.addActionListener(al);
    }
    
    public void addBtnNormativasListener(ActionListener al){
        btnNormativa.addActionListener(al);
    }
    
    public void addBtnDivisionesListener(ActionListener al){
        btnDivisiones.addActionListener(al);
    }
    
    public void addBtnLicenciasListener(ActionListener al){
        btnLicencias.addActionListener(al);
    }
    
    public void addBtnInformesListener(ActionListener al){
        btnInformes.addActionListener(al);
    }
    
    public void addBtnCerrarSesionListener(ActionListener al){
        btnCerrarSesion.addActionListener(al);
    }
    
    public void addBtnEstadisticasListener(ActionListener al){
        btnEstadisticas.addActionListener(al);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bienvenidaLabel;
    private javax.swing.JButton btnAdministrarUsuarios;
    private javax.swing.JButton btnAnuncios;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnDivisiones;
    private javax.swing.JButton btnEstadisticas;
    private javax.swing.JButton btnInformes;
    private javax.swing.JButton btnLicencias;
    private javax.swing.JButton btnLogs;
    private javax.swing.JButton btnNormativa;
    // End of variables declaration//GEN-END:variables
}
